version: '3' 
services:
  web: 
    build: . 
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/labs_wishlist
      - SECRET_KEY="You shall not pass"
    ports: 
      - "5000:5000"
    depends_on: 
      - db
  db: 
    image: postgres:latest 
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/var/lib/postgresql/data
  
